apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-application
  annotations:
    backstage.io/kubernetes-label-selector: app:blackduck
    backstage.io/kubernetes-namespace: bd
    backstage.io/kubernetes-cluster: aksbdhpoc
spec:
  type: service
  owner: team-a
  lifecycle: production
